# Generated by Django 5.2.13 on 2026-05-14 17:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=200, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de naissance"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nom d'utilisateur",
                    ),
                ),
                (
                    "role_global",
                    models.CharField(
                        choices=[
                            ("pdg", "PDG - Accès total"),
                            ("drh", "DRH - Gestion RH toutes agences"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=20,
                        verbose_name="Rôle global",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Département"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Téléphone"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Adresse"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ville"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="France",
                        max_length=100,
                        null=True,
                        verbose_name="Pays",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Code postal"
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Matricule",
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'embauche"
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Type de contrat",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Salaire",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Dernière IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pictures/",
                        verbose_name="Photo de profil",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
                "permissions": [
                    ("can_view_reports", "Peut voir les rapports"),
                    ("can_manage_users", "Peut gérer les utilisateurs"),
                    ("can_validate_orders", "Peut valider les commandes"),
                    ("can_manage_inventory", "Peut gérer l'inventaire"),
                    ("can_manage_rh", "Peut gérer les ressources humaines"),
                    ("can_view_all_agences", "Peut voir toutes les agences"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Agence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=200, verbose_name="Nom de l'agence"),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="Code agence",
                    ),
                ),
                (
                    "type_agence",
                    models.CharField(
                        choices=[
                            ("principale", "Agence Principale"),
                            ("secondaire", "Agence Secondaire"),
                        ],
                        default="principale",
                        max_length=20,
                        verbose_name="Type d'agence",
                    ),
                ),
                ("adresse", models.TextField(verbose_name="Adresse")),
                (
                    "telephone",
                    models.CharField(max_length=20, verbose_name="Téléphone"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("ville", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "code_postal",
                    models.CharField(max_length=20, verbose_name="Code postal"),
                ),
                (
                    "pays",
                    models.CharField(
                        default="France", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "est_active",
                    models.BooleanField(default=True, verbose_name="Agence active"),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agences_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agence",
                "verbose_name_plural": "Agences",
                "ordering": ["-type_agence", "nom"],
                "permissions": [
                    ("can_create_agence", "Peut créer une agence"),
                    ("can_edit_agence", "Peut modifier une agence"),
                    ("can_delete_agence", "Peut supprimer une agence"),
                    ("can_view_all_agences", "Peut voir toutes les agences"),
                ],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="agence_principale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateurs_principaux",
                to="users.agence",
                verbose_name="Agence principale",
            ),
        ),
        migrations.CreateModel(
            name="RoleAgence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("chef_agence", "Chef d'agence"),
                            ("gestionnaire_stock", "Gestionnaire de stock"),
                            ("commercial", "Commercial"),
                        ],
                        max_length=20,
                        verbose_name="Rôle",
                    ),
                ),
                (
                    "date_attribution",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'attribution"
                    ),
                ),
                (
                    "est_actif",
                    models.BooleanField(default=True, verbose_name="Rôle actif"),
                ),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="users.agence",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles_agence",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rôle par agence",
                "verbose_name_plural": "Rôles par agence",
                "ordering": ["agence", "user"],
                "unique_together": {("user", "agence", "role")},
            },
        ),
    ]
