# Generated by Django 5.2.13 on 2026-07-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_view_reports", "Peut voir les rapports"),
                    ("can_manage_users", "Peut gérer les utilisateurs"),
                    ("can_validate_orders", "Peut valider les commandes"),
                    ("can_manage_inventory", "Peut gérer l'inventaire"),
                    ("can_manage_rh", "Peut gérer les ressources humaines"),
                    ("can_view_all_agences", "Peut voir toutes les agences"),
                    ("can_manage_accounting", "Peut gérer la comptabilité"),
                ],
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name="roleagence",
            name="role",
            field=models.CharField(
                choices=[
                    ("chef_agence", "Chef d'agence"),
                    ("gestionnaire_stock", "Gestionnaire de stock"),
                    ("commercial", "Commercial"),
                    ("comptable", "Comptable"),
                ],
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
