# Generated by Django 5.2.13 on 2026-05-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True,
                default="Sénégal",
                max_length=100,
                null=True,
                verbose_name="Pays",
            ),
        ),
    ]
