# Generated by Django 5.2.13 on 2026-04-24 16:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventaire", "0001_initial"),
        ("produits", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_preferred", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Transporteur",
                "verbose_name_plural": "Transporteurs",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=50, unique=True)),
                (
                    "supplier_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Réf. fournisseur",
                    ),
                ),
                ("order_date", models.DateField(auto_now_add=True)),
                (
                    "expected_date",
                    models.DateField(verbose_name="Date de livraison prévue"),
                ),
                ("confirmed_date", models.DateField(blank=True, null=True)),
                (
                    "shipped_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'expédition"
                    ),
                ),
                (
                    "received_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de réception"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyée au fournisseur"),
                            ("confirmed", "Confirmée"),
                            ("in_transit", "En transit"),
                            ("partially_received", "Partiellement reçue"),
                            ("received", "Reçue complètement"),
                            ("cancelled", "Annulée"),
                            ("rejected", "Rejetée"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("urgent", "Urgent"),
                            ("very_urgent", "Très urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="XOF", max_length=10)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
                ),
                ("shipping_address", models.TextField(blank=True, default="")),
                (
                    "shipping_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("carrier", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "order_file",
                    models.FileField(
                        blank=True, null=True, upload_to="purchase_orders/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("internal_notes", models.TextField(blank=True, null=True)),
                ("terms_conditions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="users.agence",
                        verbose_name="Agence destinataire",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_purchase_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_orders",
                        to="inventaire.warehouse",
                        verbose_name="Entrepôt de réception",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date", "-order_number"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_reference",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Réf. fournisseur",
                    ),
                ),
                (
                    "quantity_ordered",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("quantity_received", models.IntegerField(default=0)),
                ("quantity_invoiced", models.IntegerField(default=0)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "discount_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=20, max_digits=5),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produits.product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchases.purchaseorder",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("receipt_date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "document",
                    models.FileField(
                        blank=True, null=True, upload_to="purchase_receipts/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="purchases.purchaseorder",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-receipt_date"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("quality_checked", models.BooleanField(default=False)),
                ("quality_ok", models.BooleanField(default=True)),
                ("quality_notes", models.TextField(blank=True, null=True)),
                ("lot_number", models.CharField(blank=True, max_length=100, null=True)),
                ("serial_numbers", models.JSONField(blank=True, default=list)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchases.purchaseorderitem",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchases.purchasereceipt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiptCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("transport", "Transport"),
                            ("customs_duty", "Droits de douane"),
                            ("customs_clearance", "Frais de dédouanement"),
                            ("insurance", "Assurance"),
                            ("handling", "Frais de manutention"),
                            ("storage", "Frais de stockage"),
                            ("port_fees", "Frais portuaires"),
                            ("transit_fees", "Frais de transit"),
                            ("other", "Autres frais"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="XOF", max_length=10)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
                ),
                (
                    "amount_in_local_currency",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="N° de référence",
                    ),
                ),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="receipt_costs/"),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=True, verbose_name="Facturable au client"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="purchases.purchasereceipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Frais de réception",
                "verbose_name_plural": "Frais de réception",
                "ordering": ["cost_type"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code fournisseur"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Raison sociale"),
                ),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("manufacturer", "Fabricant"),
                            ("distributor", "Distributeur"),
                            ("wholesaler", "Grossiste"),
                            ("importer", "Importateur"),
                            ("service", "Prestataire de services"),
                        ],
                        default="distributor",
                        max_length=20,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="N° RC/RCCM"
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="N° TVA/IFU"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        max_length=200, verbose_name="Personne de contact"
                    ),
                ),
                (
                    "contact_title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Fonction"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("fax", models.CharField(blank=True, max_length=20, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("address", models.TextField()),
                (
                    "address_line2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="Sénégal", max_length=100)),
                ("bank_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "bank_account",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="N° compte"
                    ),
                ),
                (
                    "bank_swift",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Code SWIFT/BIC",
                    ),
                ),
                (
                    "bank_iban",
                    models.CharField(
                        blank=True, max_length=34, null=True, verbose_name="IBAN"
                    ),
                ),
                (
                    "payment_terms",
                    models.CharField(
                        choices=[
                            ("immediate", "Paiement immédiat"),
                            ("15_days", "15 jours"),
                            ("30_days", "30 jours"),
                            ("45_days", "45 jours"),
                            ("60_days", "60 jours"),
                            ("end_of_month", "Fin de mois"),
                        ],
                        default="30_days",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_terms",
                    models.CharField(
                        choices=[
                            ("exw", "EXW - Départ usine"),
                            ("fca", "FCA - Franco transporteur"),
                            ("fas", "FAS - Franco le long du navire"),
                            ("fob", "FOB - Franco à bord"),
                            ("cfr", "CFR - Coût et fret"),
                            ("cif", "CIF - Coût, assurance et fret"),
                            ("dap", "DAP - Rendu au lieu de destination"),
                            ("ddu", "DDU - Droits non acquittés"),
                            ("ddd", "DDD - Droits acquittés"),
                        ],
                        default="exw",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="XOF", max_length=10, verbose_name="Devise"
                    ),
                ),
                (
                    "lead_time_days",
                    models.IntegerField(
                        default=7, verbose_name="Délai de livraison (jours)"
                    ),
                ),
                (
                    "minimum_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Montant minimum de commande",
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Remise (%)",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="Note (1-5)",
                    ),
                ),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False, verbose_name="Fournisseur préféré"
                    ),
                ),
                (
                    "performance_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Score de performance",
                    ),
                ),
                (
                    "total_orders",
                    models.IntegerField(default=0, verbose_name="Total commandes"),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total dépensé",
                    ),
                ),
                (
                    "average_delivery_delay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Retard moyen (jours)",
                    ),
                ),
                (
                    "on_time_delivery_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Taux de livraison à temps (%)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_blocked", models.BooleanField(default=False)),
                ("blocking_reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("internal_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_suppliers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_suppliers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["company_name"],
            },
        ),
        migrations.CreateModel(
            name="PurchasePriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="XOF", max_length=10)),
                ("quantity", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="produits.product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="purchases.purchaseorder",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits.productvariant",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchases.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Historiques de prix",
                "ordering": ["-date"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="purchases.supplier",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("reorder", "Réapprovisionnement nécessaire"),
                            ("supplier_outage", "Rupture fournisseur"),
                            ("price_increase", "Augmentation de prix"),
                            ("delivery_delay", "Retard de livraison"),
                            ("minimum_order", "Seuil minimum atteint"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField()),
                ("current_stock", models.IntegerField(default=0)),
                ("reorder_point", models.IntegerField(default=0)),
                ("suggested_quantity", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produits.product",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchases.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("file", models.FileField(upload_to="supplier_catalogs/")),
                (
                    "file_format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("excel", "Excel"), ("pdf", "PDF")],
                        max_length=20,
                    ),
                ),
                ("import_date", models.DateTimeField(auto_now_add=True)),
                ("products_imported", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échec"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_log", models.TextField(blank=True, null=True)),
                (
                    "imported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalogs",
                        to="purchases.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-import_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplierContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Fonction"
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="purchases.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evaluation_date", models.DateField(auto_now_add=True)),
                (
                    "quality_score",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Qualité des produits",
                    ),
                ),
                (
                    "price_score",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Prix",
                    ),
                ),
                (
                    "delivery_score",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Respect des délais",
                    ),
                ),
                (
                    "communication_score",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Communication",
                    ),
                ),
                (
                    "responsiveness_score",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        verbose_name="Réactivité",
                    ),
                ),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, editable=False, max_digits=5),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("improvement_suggestions", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evaluator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="purchases.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-evaluation_date"],
            },
        ),
        migrations.CreateModel(
            name="Waybill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("waybill_number", models.CharField(max_length=100, unique=True)),
                ("issue_date", models.DateField()),
                ("estimated_arrival", models.DateField(blank=True, null=True)),
                ("actual_arrival", models.DateField(blank=True, null=True)),
                ("customs_clearance_date", models.DateField(blank=True, null=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("origin", models.CharField(max_length=200)),
                ("destination", models.CharField(max_length=200)),
                (
                    "port_of_loading",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "port_of_discharge",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "container_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("seal_number", models.CharField(blank=True, max_length=50, null=True)),
                ("number_of_packages", models.IntegerField(default=1)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "volume_m3",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("in_transit", "En transit"),
                            ("arrived", "Arrivé"),
                            ("cleared", "Dédouané"),
                            ("delivered", "Livré"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "waybill_file",
                    models.FileField(blank=True, null=True, upload_to="waybills/"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_waybills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waybills",
                        to="purchases.purchaseorder",
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waybills",
                        to="purchases.transporter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon de transport",
                "verbose_name_plural": "Bons de transport",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptCostAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "allocation_method",
                    models.CharField(
                        choices=[
                            ("quantity", "Par quantité"),
                            ("weight", "Par poids"),
                            ("volume", "Par volume"),
                            ("value", "Par valeur"),
                            ("equal", "De manière égale"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="produits.product",
                    ),
                ),
                (
                    "receipt_cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="purchases.receiptcost",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allocation de frais",
                "verbose_name_plural": "Allocations de frais",
                "unique_together": {("receipt_cost", "product", "variant")},
            },
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["code"], name="purchases_s_code_ed3223_idx"),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["company_name"], name="purchases_s_company_afd7cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["is_preferred"], name="purchases_s_is_pref_ccca33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(fields=["rating"], name="purchases_s_rating_2ab991_idx"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["order_number"], name="purchases_p_order_n_2fe609_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["supplier", "status"], name="purchases_p_supplie_1eb951_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["expected_date"], name="purchases_p_expecte_ad6b41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["agence"], name="purchases_p_agence__68fe5e_idx"
            ),
        ),
    ]
