# Generated by Django 5.2.13 on 2026-08-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0002_initial"),
        ("tresorerie", "0002_frais_caisse_destination_frais_compte_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasereceipt",
            name="caisse_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receptions_achats",
                to="tresorerie.caisse",
                verbose_name="Caisse de décaissement",
            ),
        ),
        migrations.AddField(
            model_name="purchasereceipt",
            name="compte_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receptions_achats",
                to="tresorerie.comptebancaire",
                verbose_name="Compte bancaire de décaissement",
            ),
        ),
        migrations.AddField(
            model_name="purchasereceipt",
            name="mouvement_tresorerie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reception_achat",
                to="tresorerie.mouvementtresorerie",
                verbose_name="Mouvement de trésorerie associé",
            ),
        ),
    ]
