# Generated by Django 5.2.13 on 2026-08-08 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0003_purchasereceipt_caisse_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasereceiptitem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
