# Generated by Django 5.2.13 on 2026-07-22 20:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expenseclaim",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Note de frais",
                "verbose_name_plural": "Notes de frais",
            },
        ),
        migrations.RemoveField(
            model_name="expenseclaim",
            name="employee",
        ),
    ]
