# Generated by Django 5.2.13 on 2026-07-22 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0003_alter_expenseclaim_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expenseclaim",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "can_validate_expense",
                        "Peut valider une note de frais (RH/Manager)",
                    ),
                    ("can_pay_expense", "Peut payer une note de frais (Comptable)"),
                ],
                "verbose_name": "Note de frais",
                "verbose_name_plural": "Notes de frais",
            },
        ),
        migrations.RenameField(
            model_name="expenseclaim",
            old_name="approval_date",
            new_name="validation_date",
        ),
        migrations.RemoveField(
            model_name="expenseclaim",
            name="approved_by",
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paid_expenses",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="validated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validated_expenses",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="expenseclaim",
            name="validation_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expenseclaim",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente de validation RH"),
                    ("approved", "Validé par RH - En attente de paiement"),
                    ("paid", "Payé par Comptabilité"),
                    ("rejected", "Rejeté"),
                    ("cancelled", "Annulé"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
