# Generated by Django 5.2.13 on 2026-05-08 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventaire", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transfer",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="rejected_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("pending_approval", "En attente d'approbation"),
                    ("approved", "Approuvé"),
                    ("rejected", "Rejeté"),
                    ("in_transit", "En transit"),
                    ("partial", "Partiellement reçu"),
                    ("completed", "Terminé"),
                    ("cancelled", "Annulé"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["from_warehouse", "to_warehouse"],
                name="inventaire__from_wa_717f87_idx",
            ),
        ),
    ]
