# Generated by Django 5.2.13 on 2026-05-08 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventaire", "0002_transfer_approved_at_transfer_approved_by_and_more"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="transfer",
            name="inventaire__from_wa_717f87_idx",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="from_warehouse",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="to_warehouse",
        ),
        migrations.AddField(
            model_name="transfer",
            name="from_agence",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers_from",
                to="users.agence",
                verbose_name="Agence source",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transfer",
            name="to_agence",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers_to",
                to="users.agence",
                verbose_name="Agence destination",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="transfer",
            index=models.Index(
                fields=["from_agence", "to_agence"],
                name="inventaire__from_ag_f9dad6_idx",
            ),
        ),
    ]
