# Generated by Django 5.2.13 on 2026-09-18 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventaire", "0002_initial"),
        ("users", "0002_alter_customuser_options_alter_roleagence_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="warehouse",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unique_warehouse_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("agence",),
                name="unique_default_warehouse_per_agence",
            ),
        ),
    ]
