# Generated by Django 5.2.13 on 2026-09-20 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventaire", "0003_alter_warehouse_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorycount",
            name="reference",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reference",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="reference",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="inventorycount",
            index=models.Index(
                fields=["reference"], name="inventaire__referen_5264de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventorycount",
            index=models.Index(fields=["status"], name="inventaire__status_6f4dc3_idx"),
        ),
        migrations.AddIndex(
            model_name="inventorycount",
            index=models.Index(
                fields=["warehouse", "count_date"],
                name="inventaire__warehou_920d5c_idx",
            ),
        ),
    ]
