# Generated by Django 5.2.13 on 2026-07-23 14:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("purchases", "0002_initial"),
        ("sales", "0002_initial"),
        ("users", "0002_alter_customuser_options_alter_roleagence_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyseFinanciere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "type_analyse",
                    models.CharField(
                        choices=[
                            ("ratio", "Ratio"),
                            ("tendance", "Tendance"),
                            ("comparaison", "Comparaison"),
                            ("prevision", "Prévision"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("titre", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "donnees",
                    models.JSONField(default=dict, verbose_name="Données de l'analyse"),
                ),
                (
                    "resultat",
                    models.JSONField(
                        default=dict, verbose_name="Résultat de l'analyse"
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date début")),
                ("date_fin", models.DateField(verbose_name="Date fin")),
                (
                    "date_analyse",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date analyse"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="analyses",
                        to="users.agence",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyse financière",
                "verbose_name_plural": "Analyses financières",
                "ordering": ["-date_analyse"],
            },
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "type_balance",
                    models.CharField(
                        choices=[
                            ("generale", "Balance générale"),
                            ("comptes", "Balance des comptes"),
                            ("agee", "Balance âgée"),
                        ],
                        default="generale",
                        max_length=20,
                        verbose_name="Type de balance",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date début")),
                ("date_fin", models.DateField(verbose_name="Date fin")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("valide", "Validée"),
                            ("archive", "Archivée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balances",
                        to="users.agence",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="balances_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Balance",
                "verbose_name_plural": "Balances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FactureComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "type_facture",
                    models.CharField(
                        choices=[("client", "Client"), ("fournisseur", "Fournisseur")],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "date_facture",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date facture"
                    ),
                ),
                ("date_echeance", models.DateField(verbose_name="Date échéance")),
                (
                    "montant_ht",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant HT",
                    ),
                ),
                (
                    "montant_tva",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant TVA",
                    ),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant TTC",
                    ),
                ),
                (
                    "montant_paye",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "montant_restant",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Montant restant",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("envoyee", "Envoyée"),
                            ("recue", "Reçue"),
                            ("payee", "Payée"),
                            ("partielle", "Partiellement payée"),
                            ("impayee", "Impayée"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_rapprochement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date rapprochement"
                    ),
                ),
                (
                    "rapproche",
                    models.BooleanField(default=False, verbose_name="Rapproché"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "achat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factures_comptables",
                        to="purchases.purchaseorder",
                        verbose_name="Achat",
                    ),
                ),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="factures_comptables",
                        to="users.agence",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factures_comptables",
                        to="sales.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factures_comptables_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factures_comptables",
                        to="purchases.supplier",
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factures_comptables",
                        to="sales.vente",
                        verbose_name="Vente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture comptable",
                "verbose_name_plural": "Factures comptables",
                "ordering": ["-date_facture"],
            },
        ),
        migrations.CreateModel(
            name="IndicateurFinancier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "type_indicateur",
                    models.CharField(
                        choices=[
                            ("tresorerie", "Trésorerie"),
                            ("profitabilite", "Profitabilité"),
                            ("liquidite", "Liquidité"),
                            ("endettement", "Endettement"),
                            ("rotation", "Rotation"),
                            ("marge", "Marge"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Code"),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valeur",
                    ),
                ),
                (
                    "valeur_previous",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Valeur précédente",
                    ),
                ),
                (
                    "date_calcul",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date calcul"
                    ),
                ),
                ("periode_debut", models.DateField(verbose_name="Période début")),
                ("periode_fin", models.DateField(verbose_name="Période fin")),
                (
                    "formule",
                    models.TextField(
                        blank=True, null=True, verbose_name="Formule de calcul"
                    ),
                ),
                (
                    "interpretation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Interprétation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="indicateurs",
                        to="users.agence",
                        verbose_name="Agence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicateur financier",
                "verbose_name_plural": "Indicateurs financiers",
                "ordering": ["type_indicateur", "code"],
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Code journal"
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=100, verbose_name="Nom du journal"),
                ),
                (
                    "type_journal",
                    models.CharField(
                        choices=[
                            ("achats", "Achats"),
                            ("ventes", "Ventes"),
                            ("banque", "Banque"),
                            ("caisse", "Caisse"),
                            ("od", "Opérations diverses"),
                            ("inventaire", "Inventaire"),
                            ("paie", "Paie"),
                            ("immobilisations", "Immobilisations"),
                        ],
                        max_length=20,
                        verbose_name="Type de journal",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="Journal par défaut"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journaux",
                        to="users.agence",
                        verbose_name="Agence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journaux",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Ecriture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "date_ecriture",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date d'écriture",
                    ),
                ),
                (
                    "date_comptable",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date comptable"
                    ),
                ),
                ("libelle", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "piece_justificative",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Pièce justificative",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Type de source",
                    ),
                ),
                (
                    "source_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID source"
                    ),
                ),
                (
                    "total_debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total débit",
                    ),
                ),
                (
                    "total_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total crédit",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("valide", "Validée"),
                            ("annulee", "Annulée"),
                            ("cloturee", "Clôturée"),
                        ],
                        default="brouillon",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date validation"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecritures",
                        to="users.agence",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecritures_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ecritures_validees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ecritures",
                        to="comptabilite.journal",
                        verbose_name="Journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture",
                "verbose_name_plural": "Écritures",
                "ordering": ["-date_ecriture", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Code compte"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom du compte")),
                (
                    "type_compte",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("passif", "Passif"),
                            ("capitaux", "Capitaux propres"),
                            ("charges", "Charges"),
                            ("produits", "Produits"),
                        ],
                        max_length=20,
                        verbose_name="Type de compte",
                    ),
                ),
                ("niveau", models.IntegerField(default=1, verbose_name="Niveau")),
                (
                    "classe",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Classe"
                    ),
                ),
                (
                    "sous_classe",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Sous-classe"
                    ),
                ),
                (
                    "solde_normal",
                    models.CharField(
                        choices=[("debiteur", "Débiteur"), ("crediteur", "Créditeur")],
                        default="debiteur",
                        max_length=10,
                        verbose_name="Solde normal",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "is_analytique",
                    models.BooleanField(
                        default=False, verbose_name="Compte analytique"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comptes_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sous_comptes",
                        to="comptabilite.plancomptable",
                        verbose_name="Compte parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan comptable",
                "verbose_name_plural": "Plan comptable",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LigneEcriture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Débit"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Crédit",
                    ),
                ),
                (
                    "libelle",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Libellé ligne",
                    ),
                ),
                (
                    "lettrage",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Lettrage"
                    ),
                ),
                (
                    "date_lettrage",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date lettrage"
                    ),
                ),
                (
                    "centre_analytique",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Centre analytique",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ecriture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="comptabilite.ecriture",
                        verbose_name="Écriture",
                    ),
                ),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes",
                        to="comptabilite.plancomptable",
                        verbose_name="Compte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne d'écriture",
                "verbose_name_plural": "Lignes d'écriture",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="LigneBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solde_initial_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "solde_initial_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "mouvement_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "mouvement_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "solde_final_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "solde_final_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="comptabilite.balance",
                        verbose_name="Balance",
                    ),
                ),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes_balance",
                        to="comptabilite.plancomptable",
                        verbose_name="Compte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de balance",
                "verbose_name_plural": "Lignes de balance",
                "ordering": ["compte__code"],
            },
        ),
        migrations.CreateModel(
            name="Reglement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "type_reglement",
                    models.CharField(
                        choices=[("client", "Client"), ("fournisseur", "Fournisseur")],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant",
                    ),
                ),
                (
                    "mode_reglement",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("carte", "Carte bancaire"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("mobile_money", "Mobile Money"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Mode",
                    ),
                ),
                (
                    "date_reglement",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date règlement"
                    ),
                ),
                (
                    "reference_externe",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Référence externe",
                    ),
                ),
                (
                    "date_rapprochement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date rapprochement"
                    ),
                ),
                (
                    "rapproche",
                    models.BooleanField(default=False, verbose_name="Rapproché"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reglements",
                        to="users.agence",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reglements",
                        to="sales.client",
                        verbose_name="Client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reglements_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reglements",
                        to="comptabilite.facturecomptable",
                        verbose_name="Facture",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reglements",
                        to="purchases.supplier",
                        verbose_name="Fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règlement",
                "verbose_name_plural": "Règlements",
                "ordering": ["-date_reglement"],
            },
        ),
        migrations.CreateModel(
            name="SoldeCompte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_solde", models.DateField(verbose_name="Date du solde")),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Débit"
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Crédit",
                    ),
                ),
                (
                    "solde",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=15, verbose_name="Solde"
                    ),
                ),
                (
                    "debit_periode",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Débit période",
                    ),
                ),
                (
                    "credit_periode",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Crédit période",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="soldes_comptes",
                        to="users.agence",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="soldes",
                        to="comptabilite.plancomptable",
                        verbose_name="Compte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solde de compte",
                "verbose_name_plural": "Soldes de comptes",
                "ordering": ["compte__code", "-date_solde"],
            },
        ),
        migrations.CreateModel(
            name="ClotureComptable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "type_cloture",
                    models.CharField(
                        choices=[
                            ("mensuelle", "Mensuelle"),
                            ("trimestrielle", "Trimestrielle"),
                            ("annuelle", "Annuelle"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("date_debut", models.DateField(verbose_name="Date début")),
                ("date_fin", models.DateField(verbose_name="Date fin")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ouverte", "Ouverte"),
                            ("en_cours", "En cours"),
                            ("cloturee", "Clôturée"),
                            ("verrouillee", "Verrouillée"),
                        ],
                        default="ouverte",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "total_debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total débit",
                    ),
                ),
                (
                    "total_credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Total crédit",
                    ),
                ),
                (
                    "resultat_exercice",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="Résultat exercice",
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date fermeture"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clotures",
                        to="users.agence",
                        verbose_name="Agence",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clotures_fermees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Fermé par",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clotures_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clôture comptable",
                "verbose_name_plural": "Clôtures comptables",
                "ordering": ["-date_fin"],
                "unique_together": {("agence", "date_debut", "date_fin")},
            },
        ),
        migrations.AddIndex(
            model_name="facturecomptable",
            index=models.Index(
                fields=["reference"], name="comptabilit_referen_77fdd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facturecomptable",
            index=models.Index(
                fields=["type_facture", "status"], name="comptabilit_type_fa_b87357_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="facturecomptable",
            index=models.Index(
                fields=["date_facture", "date_echeance"],
                name="comptabilit_date_fa_42d900_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="journal",
            unique_together={("agence", "code")},
        ),
        migrations.AddIndex(
            model_name="ecriture",
            index=models.Index(
                fields=["reference"], name="comptabilit_referen_d7c75f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ecriture",
            index=models.Index(
                fields=["date_ecriture"], name="comptabilit_date_ec_232d64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ecriture",
            index=models.Index(
                fields=["journal", "status"], name="comptabilit_journal_2d917a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ecriture",
            index=models.Index(
                fields=["agence", "date_ecriture"],
                name="comptabilit_agence__9699e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reglement",
            index=models.Index(
                fields=["reference"], name="comptabilit_referen_c2993d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reglement",
            index=models.Index(
                fields=["type_reglement", "date_reglement"],
                name="comptabilit_type_re_86d439_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="soldecompte",
            unique_together={("compte", "agence", "date_solde")},
        ),
    ]
