# Generated by Django 5.2.13 on 2026-04-21 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("nombre_jours_par_an", models.PositiveIntegerField(default=25)),
                ("est_paye", models.BooleanField(default=True)),
                ("est_actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Type de congé",
                "verbose_name_plural": "Types de congés",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("est_actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departements_drh",
                        to="users.agence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
                "ordering": ["agence", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=50, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                ("date_naissance", models.DateField()),
                ("lieu_naissance", models.CharField(max_length=100)),
                ("nationalite", models.CharField(default="Sénégalaise", max_length=50)),
                ("numero_cni", models.CharField(blank=True, max_length=50)),
                (
                    "situation_familiale",
                    models.CharField(
                        choices=[
                            ("celibataire", "Célibataire"),
                            ("marie", "Marié(e)"),
                            ("divorce", "Divorcé(e)"),
                            ("veuf", "Veuf/Veuve"),
                        ],
                        default="celibataire",
                        max_length=20,
                    ),
                ),
                ("nombre_enfants", models.PositiveIntegerField(default=0)),
                ("telephone_urgence", models.CharField(blank=True, max_length=20)),
                ("contact_urgence", models.CharField(blank=True, max_length=100)),
                ("adresse", models.TextField(blank=True)),
                ("ville", models.CharField(blank=True, max_length=100)),
                ("code_postal", models.CharField(blank=True, max_length=20)),
                ("pays", models.CharField(default="Sénégal", max_length=50)),
                ("banque", models.CharField(blank=True, max_length=100)),
                ("rib", models.CharField(blank=True, max_length=50)),
                ("est_actif", models.BooleanField(default=True)),
                ("date_embauche", models.DateField()),
                ("date_depart", models.DateField(blank=True, null=True)),
                ("motif_depart", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="employes/photos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employes_drh",
                        to="users.agence",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employes_crees_drh",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employes",
                        to="drh.departement",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employe_drh",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Contrat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_contrat",
                    models.CharField(
                        choices=[
                            ("cdi", "CDI"),
                            ("cdd", "CDD"),
                            ("stage", "Stage"),
                            ("interim", "Intérim"),
                            ("prestation", "Prestation"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("en_attente", "En attente de signature"),
                            ("signe", "Signé"),
                            ("en_cours", "En cours"),
                            ("termine", "Terminé"),
                            ("resilie", "Résilié"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("date_signature", models.DateField(blank=True, null=True)),
                ("salaire_brut", models.DecimalField(decimal_places=2, max_digits=10)),
                ("lieu_travail", models.CharField(blank=True, max_length=200)),
                (
                    "document",
                    models.FileField(blank=True, null=True, upload_to="contrats/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrats",
                        to="drh.employe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrat",
                "verbose_name_plural": "Contrats",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Absence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_absence",
                    models.CharField(
                        choices=[
                            ("maladie", "Maladie"),
                            ("accident_travail", "Accident de travail"),
                            ("maternite", "Congé maternité"),
                            ("non_justifiee", "Absence non justifiée"),
                            ("formation", "Formation"),
                            ("mission", "Mission"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("justifiee", models.BooleanField(default=False)),
                (
                    "justificatif",
                    models.FileField(blank=True, null=True, upload_to="absences/"),
                ),
                ("commentaire", models.TextField(blank=True)),
                ("est_validee", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="absences",
                        to="drh.employe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Absence",
                "verbose_name_plural": "Absences",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("duree_heures", models.PositiveIntegerField(default=0)),
                ("formateur", models.CharField(blank=True, max_length=100)),
                ("organisme", models.CharField(blank=True, max_length=100)),
                ("lieu", models.CharField(blank=True, max_length=200)),
                (
                    "cout",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifiee", "Planifiée"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("annulee", "Annulée"),
                        ],
                        default="planifiee",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation",
                "verbose_name_plural": "Formations",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Pointage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_pointage",
                    models.CharField(
                        choices=[("entree", "Entrée"), ("sortie", "Sortie")],
                        max_length=20,
                    ),
                ),
                ("date_heure", models.DateTimeField(auto_now_add=True)),
                ("commentaire", models.TextField(blank=True)),
                ("est_valide", models.BooleanField(default=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pointages",
                        to="drh.employe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pointage",
                "verbose_name_plural": "Pointages",
                "ordering": ["-date_heure"],
            },
        ),
        migrations.CreateModel(
            name="Poste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("junior", "Junior"),
                            ("confirme", "Confirmé"),
                            ("senior", "Senior"),
                            ("expert", "Expert"),
                            ("manager", "Manager"),
                            ("directeur", "Directeur"),
                        ],
                        default="junior",
                        max_length=20,
                    ),
                ),
                ("salaire_min", models.DecimalField(decimal_places=2, max_digits=10)),
                ("salaire_max", models.DecimalField(decimal_places=2, max_digits=10)),
                ("competences_requises", models.TextField(blank=True)),
                ("est_actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="postes",
                        to="drh.departement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Poste",
                "verbose_name_plural": "Postes",
                "ordering": ["departement", "niveau", "nom"],
            },
        ),
        migrations.AddField(
            model_name="employe",
            name="poste",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employes",
                to="drh.poste",
            ),
        ),
        migrations.CreateModel(
            name="DemandeConge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("nombre_jours", models.DecimalField(decimal_places=1, max_digits=5)),
                ("motif", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("en_attente", "En attente"),
                            ("validee", "Validée"),
                            ("refusee", "Refusée"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("motif_refus", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_conges",
                        to="drh.employe",
                    ),
                ),
                (
                    "type_conge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes",
                        to="drh.typeconge",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de congé",
                "verbose_name_plural": "Demandes de congés",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="ParticipationFormation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                (
                    "resultat",
                    models.CharField(
                        choices=[
                            ("inscrit", "Inscrit"),
                            ("present", "Présent"),
                            ("absent", "Absent"),
                            ("reussi", "Réussi"),
                            ("echoue", "Échoué"),
                        ],
                        default="inscrit",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "certificat",
                    models.FileField(
                        blank=True, null=True, upload_to="formations/certificats/"
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drh.employe"
                    ),
                ),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="drh.formation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation à une formation",
                "verbose_name_plural": "Participations aux formations",
                "unique_together": {("employe", "formation")},
            },
        ),
    ]
