# Generated by Django 5.2.13 on 2026-05-19 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productpricing",
            unique_together=set(),
        ),
    ]
