# Generated by Django 5.2.13 on 2026-09-20 17:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productpricing",
            name="tax_rate",
        ),
    ]
