# Generated by Django 5.2.13 on 2026-07-04 23:28

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("particulier", "Particulier"),
                            ("entreprise", "Entreprise"),
                            ("revendeur", "Revendeur"),
                        ],
                        default="particulier",
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("prenom", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone", models.CharField(max_length=20)),
                ("adresse", models.TextField(blank=True, null=True)),
                (
                    "raison_sociale",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("numero_tva", models.CharField(blank=True, max_length=50, null=True)),
                ("est_revendeur", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Devis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("accepted", "Accepté"),
                            ("refused", "Refusé"),
                            ("converted", "Converti en vente"),
                            ("expired", "Expiré"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_expiration", models.DateField()),
                (
                    "sous_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remise_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "conditions",
                    models.TextField(
                        blank=True, help_text="Conditions générales du devis", null=True
                    ),
                ),
                ("pied_de_page", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="DevisItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "type_facture",
                    models.CharField(
                        choices=[
                            ("proforma", "Proforma"),
                            ("finale", "Finale"),
                            ("avoir", "Avoir"),
                        ],
                        default="finale",
                        max_length=20,
                    ),
                ),
                ("date_facture", models.DateField(default=django.utils.timezone.now)),
                ("date_echeance", models.DateField()),
                (
                    "sous_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_ttc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "montant_restant",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="XOF", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyée"),
                            ("paid", "Payée"),
                            ("partially_paid", "Partiellement payée"),
                            ("overdue", "En retard"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "conditions_paiement",
                    models.TextField(default="Paiement à 30 jours"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("pied_de_page", models.TextField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="factures/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
                "ordering": ["-date_facture"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=50, unique=True)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("carte", "Carte bancaire"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("mobile_money", "Mobile Money"),
                            ("autre", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_paiement", models.DateField(auto_now_add=True)),
                (
                    "reference_externe",
                    models.CharField(
                        blank=True,
                        help_text="Référence du paiement (numéro de chèque, de virement, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("completed", "Complété"),
                            ("failed", "Échoué"),
                            ("refunded", "Remboursé"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "type_vente",
                    models.CharField(
                        choices=[
                            ("comptoir", "Comptoir"),
                            ("livraison", "Livraison"),
                            ("en_ligne", "En ligne"),
                        ],
                        default="comptoir",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("pending_approval", "En attente d'approbation"),
                            ("approved", "Approuvée"),
                            ("rejected", "Rejetée"),
                            ("completed", "Complétée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("date_vente", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_approbation", models.DateTimeField(blank=True, null=True)),
                (
                    "sous_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remise_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "montant_du",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("est_paye", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("motif_rejet", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_vente"],
            },
        ),
        migrations.CreateModel(
            name="VenteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("stock_preleve", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
