# Generated by Django 5.2.13 on 2026-05-19 17:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventaire", "0002_initial"),
        ("produits", "0002_alter_productpricing_unique_together"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("particulier", "Particulier"),
                            ("entreprise", "Entreprise"),
                            ("revendeur", "Revendeur"),
                        ],
                        default="particulier",
                        max_length=20,
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("prenom", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone", models.CharField(max_length=20)),
                ("adresse", models.TextField(blank=True, null=True)),
                (
                    "raison_sociale",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("numero_tva", models.CharField(blank=True, max_length=50, null=True)),
                ("est_revendeur", models.BooleanField(default=False)),
                ("prix_speciaux", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Devis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("sent", "Envoyé"),
                            ("accepted", "Accepté"),
                            ("rejected", "Rejeté"),
                            ("expired", "Expiré"),
                            ("converted", "Converti en vente"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("date_devis", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_validite", models.DateField(blank=True, null=True)),
                (
                    "sous_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devis",
                        to="users.agence",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sales.client",
                    ),
                ),
                (
                    "createur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="devis",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_devis"],
            },
        ),
        migrations.CreateModel(
            name="DevisItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "devis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.devis",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produits.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits.productvariant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "type_vente",
                    models.CharField(
                        choices=[
                            ("comptoir", "Comptoir"),
                            ("livraison", "Livraison"),
                            ("en_ligne", "En ligne"),
                        ],
                        default="comptoir",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("pending_approval", "En attente d'approbation"),
                            ("approved", "Approuvée"),
                            ("rejected", "Rejetée"),
                            ("completed", "Complétée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("date_vente", models.DateTimeField(default=django.utils.timezone.now)),
                ("date_approbation", models.DateTimeField(blank=True, null=True)),
                (
                    "sous_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remise_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "montant_du",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("est_paye", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("motif_rejet", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventes",
                        to="users.agence",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_ventes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ventes",
                        to="sales.client",
                    ),
                ),
                (
                    "vendeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_vente"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "methode",
                    models.CharField(
                        choices=[
                            ("especes", "Espèces"),
                            ("carte", "Carte bancaire"),
                            ("cheque", "Chèque"),
                            ("virement", "Virement"),
                            ("mobile_money", "Mobile Money"),
                            ("mixte", "Mixte"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("completed", "Complété"),
                            ("failed", "Échoué"),
                            ("refunded", "Remboursé"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "date_paiement",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "encaisse_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="encaissements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="sales.vente",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_paiement"],
            },
        ),
        migrations.AddField(
            model_name="devis",
            name="vente_converted",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales.vente",
            ),
        ),
        migrations.CreateModel(
            name="VenteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("stock_preleve", models.BooleanField(default=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="produits.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="produits.productvariant",
                    ),
                ),
                (
                    "vente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.vente",
                    ),
                ),
                (
                    "warehouse_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventaire.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="vente",
            index=models.Index(
                fields=["reference"], name="sales_vente_referen_6680ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vente",
            index=models.Index(fields=["status"], name="sales_vente_status_f1cf47_idx"),
        ),
        migrations.AddIndex(
            model_name="vente",
            index=models.Index(
                fields=["agence", "status"], name="sales_vente_agence__a1b4ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vente",
            index=models.Index(
                fields=["date_vente"], name="sales_vente_date_ve_419c78_idx"
            ),
        ),
    ]
