# Generated by Django 5.2.13 on 2026-05-19 17:42

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits", "0002_alter_productpricing_unique_together"),
        ("sales", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Facture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "type_facture",
                    models.CharField(
                        choices=[
                            ("proforma", "Proforma"),
                            ("finale", "Finale"),
                            ("avoir", "Avoir"),
                        ],
                        default="finale",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("envoyee", "Envoyée"),
                            ("payee", "Payée"),
                            ("partiellement_payee", "Partiellement payée"),
                            ("en_retard", "En retard"),
                            ("annulee", "Annulée"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("date_facture", models.DateField(default=django.utils.timezone.now)),
                ("date_echeance", models.DateField()),
                (
                    "sous_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_ttc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "montant_paye",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "montant_restant",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "conditions_paiement",
                    models.TextField(default="Paiement à 30 jours"),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("pied_de_page", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date_facture"],
            },
        ),
        migrations.CreateModel(
            name="FactureItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "prix_unitaire_ht",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tva",
                    models.DecimalField(decimal_places=2, default=18, max_digits=5),
                ),
                (
                    "montant_ht",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "montant_tva",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "montant_ttc",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="devis",
            name="agence",
        ),
        migrations.RemoveField(
            model_name="devis",
            name="client",
        ),
        migrations.RemoveField(
            model_name="devis",
            name="createur",
        ),
        migrations.RemoveField(
            model_name="devis",
            name="vente_converted",
        ),
        migrations.RemoveField(
            model_name="devisitem",
            name="devis",
        ),
        migrations.RemoveField(
            model_name="devisitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="devisitem",
            name="variant",
        ),
        migrations.RemoveIndex(
            model_name="vente",
            name="sales_vente_date_ve_419c78_idx",
        ),
        migrations.RemoveField(
            model_name="client",
            name="prix_speciaux",
        ),
        migrations.AlterField(
            model_name="paiement",
            name="methode",
            field=models.CharField(
                choices=[
                    ("especes", "Espèces"),
                    ("carte", "Carte bancaire"),
                    ("cheque", "Chèque"),
                    ("virement", "Virement"),
                    ("mobile_money", "Mobile Money"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("pending", "En attente"),
                    ("completed", "Complété"),
                    ("failed", "Échoué"),
                    ("refunded", "Remboursé"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="agence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factures",
                to="users.agence",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sales.client",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="cree_par",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="factures_creees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="vente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factures",
                to="sales.vente",
            ),
        ),
        migrations.AddField(
            model_name="factureitem",
            name="facture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="sales.facture",
            ),
        ),
        migrations.AddField(
            model_name="factureitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="produits.product"
            ),
        ),
        migrations.AddField(
            model_name="factureitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="produits.productvariant",
            ),
        ),
        migrations.DeleteModel(
            name="Devis",
        ),
        migrations.DeleteModel(
            name="DevisItem",
        ),
    ]
