# Generated by Django 5.2.13 on 2026-07-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venteitem",
            name="price_type",
            field=models.CharField(
                choices=[("retail", "Prix de détail"), ("wholesale", "Prix de gros")],
                default="retail",
                max_length=20,
            ),
        ),
    ]
