# Generated by Django 5.2.13 on 2026-05-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_facture_factureitem_remove_devis_agence_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facture",
            options={
                "ordering": ["-date_facture"],
                "verbose_name": "Facture",
                "verbose_name_plural": "Factures",
            },
        ),
        migrations.RemoveField(
            model_name="facture",
            name="statut",
        ),
        migrations.AddField(
            model_name="facture",
            name="currency",
            field=models.CharField(default="XOF", max_length=10),
        ),
        migrations.AddField(
            model_name="facture",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="factures/"),
        ),
        migrations.AddField(
            model_name="facture",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("sent", "Envoyée"),
                    ("paid", "Payée"),
                    ("partially_paid", "Partiellement payée"),
                    ("overdue", "En retard"),
                    ("cancelled", "Annulée"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
