# Generated by Django 5.2.13 on 2026-05-20 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_alter_facture_options_remove_facture_statut_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="factureitem",
            name="facture",
        ),
        migrations.RemoveField(
            model_name="factureitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="factureitem",
            name="variant",
        ),
        migrations.AlterModelOptions(
            name="paiement",
            options={
                "ordering": ["-date_paiement"],
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
            },
        ),
        migrations.AddField(
            model_name="paiement",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paiements",
                to="sales.client",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paiement",
            name="facture",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paiements",
                to="sales.facture",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paiement",
            name="reference_externe",
            field=models.CharField(
                blank=True,
                help_text="Référence du paiement (numéro de chèque, de virement, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="date_paiement",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="encaisse_par",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_encaisses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="methode",
            field=models.CharField(
                choices=[
                    ("especes", "Espèces"),
                    ("carte", "Carte bancaire"),
                    ("cheque", "Chèque"),
                    ("virement", "Virement"),
                    ("mobile_money", "Mobile Money"),
                    ("autre", "Autre"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="reference",
            field=models.CharField(default=2, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="paiement",
            name="vente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paiements",
                to="sales.vente",
            ),
        ),
        migrations.AddIndex(
            model_name="paiement",
            index=models.Index(
                fields=["reference"], name="sales_paiem_referen_68abef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paiement",
            index=models.Index(
                fields=["facture", "statut"], name="sales_paiem_facture_f90798_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paiement",
            index=models.Index(
                fields=["date_paiement"], name="sales_paiem_date_pa_38f5ef_idx"
            ),
        ),
        migrations.DeleteModel(
            name="FactureItem",
        ),
    ]
