# Generated by Django 5.2.13 on 2026-07-30 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_venteitem_price_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facture",
            name="tva",
        ),
        migrations.RemoveField(
            model_name="vente",
            name="tva",
        ),
        migrations.RemoveField(
            model_name="venteitem",
            name="tva",
        ),
    ]
