# Generated by Django 5.2.13 on 2026-08-01 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_remove_facture_tva_remove_vente_tva_and_more"),
        ("tresorerie", "0002_frais_caisse_destination_frais_compte_destination"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="caisse_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_entrants_sales",
                to="tresorerie.caisse",
                verbose_name="Caisse de destination",
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="compte_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiements_entrants_sales",
                to="tresorerie.comptebancaire",
                verbose_name="Compte bancaire de destination",
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="mouvement_tresorerie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paiement_sale",
                to="tresorerie.mouvementtresorerie",
                verbose_name="Mouvement de trésorerie associé",
            ),
        ),
    ]
