# Generated by Django 5.2.13 on 2026-05-29 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_remove_factureitem_facture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="paiements",
                to="sales.client",
            ),
        ),
    ]
