# Generated by Django 5.2.13 on 2026-08-03 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventaire", "0002_initial"),
        ("sales", "0005_paiement_caisse_destination_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venteitem",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Lot prélevé pour cette ligne (si sélection manuelle)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vente_items",
                to="inventaire.lot",
            ),
        ),
    ]
