# Generated by Django 5.2.13 on 2026-06-01 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0006_devis_devisitem_devis_sales_devis_referen_bdbd2c_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="devis",
            name="tva",
        ),
        migrations.RemoveField(
            model_name="devisitem",
            name="tva",
        ),
    ]
