# Generated by Django 5.2.13 on 2026-08-01 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tresorerie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="frais",
            name="caisse_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="frais_sortants",
                to="tresorerie.caisse",
                verbose_name="Caisse de décaissement",
            ),
        ),
        migrations.AddField(
            model_name="frais",
            name="compte_destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="frais_sortants",
                to="tresorerie.comptebancaire",
                verbose_name="Compte bancaire de décaissement",
            ),
        ),
    ]
