# Generated by Django 5.2.13 on 2026-08-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tresorerie", "0002_frais_caisse_destination_frais_compte_destination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tresoreriejournaliere",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
    ]
