# Generated by Django 5.2.13 on 2026-08-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tresorerie", "0003_alter_tresoreriejournaliere_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mouvementtresorerie",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("vente", "Vente"),
                    ("achat", "Achat"),
                    ("facture_client", "Facture client"),
                    ("facture_fournisseur", "Facture fournisseur"),
                    ("reglement", "Règlement"),
                    ("ecriture", "Écriture comptable"),
                    ("salaire", "Salaire"),
                    ("frais", "Frais"),
                    ("payment", "Paiement fournisseur"),
                    ("caisse", "Caisse"),
                    ("compte_bancaire", "Compte bancaire"),
                    ("autre", "Autre"),
                ],
                max_length=20,
                verbose_name="Type source",
            ),
        ),
        migrations.AlterField(
            model_name="tresoreriejournaliere",
            name="date",
            field=models.DateField(unique=True, verbose_name="Date"),
        ),
    ]
