# Generated by Django 5.2.13 on 2026-09-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tresorerie", "0004_alter_mouvementtresorerie_source_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="frais",
            name="mode_paiement",
            field=models.CharField(
                choices=[
                    ("especes", "Espèces"),
                    ("carte", "Carte bancaire"),
                    ("cheque", "Chèque"),
                    ("virement", "Virement"),
                    ("mobile_money", "Mobile Money"),
                    ("mobile", "Mobile Money (court)"),
                    ("prelevement", "Prélèvement"),
                    ("autre", "Autre"),
                ],
                default="especes",
                max_length=20,
                verbose_name="Mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="mouvementtresorerie",
            name="mode_paiement",
            field=models.CharField(
                choices=[
                    ("especes", "Espèces"),
                    ("carte", "Carte bancaire"),
                    ("cheque", "Chèque"),
                    ("virement", "Virement"),
                    ("mobile_money", "Mobile Money"),
                    ("mobile", "Mobile Money (court)"),
                    ("prelevement", "Prélèvement"),
                    ("autre", "Autre"),
                ],
                max_length=50,
                verbose_name="Mode de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="mouvementtresorerie",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("vente", "Vente"),
                    ("achat", "Achat"),
                    ("facture_client", "Facture client"),
                    ("facture_fournisseur", "Facture fournisseur"),
                    ("reglement", "Règlement"),
                    ("ecriture", "Écriture comptable"),
                    ("salaire", "Salaire"),
                    ("frais", "Frais"),
                    ("payment", "Paiement fournisseur"),
                    ("paiement", "Paiement"),
                    ("paiement_client", "Paiement client"),
                    ("caisse", "Caisse"),
                    ("compte_bancaire", "Compte bancaire"),
                    ("autre", "Autre"),
                ],
                max_length=50,
                verbose_name="Type source",
            ),
        ),
        migrations.AlterField(
            model_name="mouvementtresorerie",
            name="status",
            field=models.CharField(
                choices=[
                    ("planifie", "Planifié"),
                    ("en_attente", "En attente"),
                    ("effectue", "Effectué"),
                    ("annule", "Annulé"),
                    ("rejete", "Rejeté"),
                ],
                default="planifie",
                max_length=50,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="mouvementtresorerie",
            name="type_mouvement",
            field=models.CharField(
                choices=[
                    ("encaissement", "Encaissement"),
                    ("decaissement", "Décaissement"),
                    ("transfert", "Transfert"),
                ],
                max_length=50,
                verbose_name="Type de mouvement",
            ),
        ),
    ]
